# Generated by Django 4.0.1 on 2022-01-30 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0004_remove_book_id_book_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='uid',
            new_name='id',
        ),
    ]
